### ISSUE TITLE
Repository entry for ::gentoo should be created with sync-git-verify-commit-signature enabled

### ISSUE THREAD

**Issue by Flowdalic** [projg2/eselect-repository#31]
https://wiki.gentoo.org/wiki/Portage_with_Git recommends `eselect repository enable gentoo` to enable git-based sync of ::gentoo. However, this leaves sync-git-verify-commit-signature *disabled*, because eselect-repository does not explicitly enable `sync-git-verify-commit-signature` for ::gentoo and portage's default is disabled.

As much as I dislike special cases, but until https://bugs.gentoo.org/901385 is fixed, eselect-repository should enable `sync-git-verify-commit-signature` when creating the repos.conf entry for ::gentoo.

**Comment by mgorny** [comment]
Wouldn't it be more prudent to have this default in Portage? We already have some signature-related bits in `/usr/share/portage/config/repos.conf`.

**Comment by Flowdalic** [comment]
> Wouldn't it be more prudent to have this default in Portage?

Only if you mean as "per repo-name default set by Portage". Not sure if `/usr/share/portage/config/repos.conf` composes with stuff under `/etc/portage/repos.conf`. That is, setting `sync-git-verify-commit-signature = true` in the `[gentoo]` section of `/usr/share/portage/config/repos.conf` would maybe have no effect once eselect-repository adds the ::gentoo repo under `/etc/portage/repos.conf`, as the latter means that the former defaults are not used at all. I am going to check if this is the case or not.

It can't be a global default, due the problematic that https://bugs.gentoo.org/901385 tries to solve. Once https://bugs.gentoo.org/901385 is fixed, the default for `sync-git-verify-commit-signature` is `if-signed`, which would do the right thing.™

**Comment by mgorny** [comment]
> It can't be a global default, due the problematic that https://bugs.gentoo.org/901385 tries to solve. Once https://bugs.gentoo.org/901385 is fixed, the default for `sync-git-verify-commit-signature` is `if-signed`, which would do the right thing.™

That doesn't solve anything. It just creates a false sense of security that can be trivially worked around by removing the signatures.

**Comment by Flowdalic** [comment]
> That doesn't solve anything. It just creates a false sense of security that can be trivially worked around by removing the signatures.

The pinning behavior described in https://bugs.gentoo.org/901385#c3 takes us already a long way. That said, it is unrelated to this issue report, so maybe we should focus on the issue that wiki.gentoo.org currently  tells users to setup git-based sync without any verification at all.

**Comment by mgorny** [comment]
I've just tested and it works when set in `[gentoo]` section of `/usr/share/portage/config/repos.conf`. Let's do it there.

**Comment by Flowdalic** [comment]
If it solves the issue, great 👍 Do you plan to submit a patch against portage?

**Comment by mgorny** [comment]
Could you do it? You seem to be doing Portage a lot these days.

**Comment by Flowdalic** [comment]
Done in https://github.com/gentoo/portage/pull/1474
